import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    // The dev server's own output. `next.config.ts` splits distDir so a local
    // `pnpm build` cannot leave a production `.next` that `pnpm dev` refuses
    // (conventions.md, "Why next.config.ts picks a different distDir for pnpm
    // dev") — but eslint-config-next only knows the default name, so lint saw
    // thousands of errors in generated bundles the moment anyone ran the dev
    // server. CI never hit it: it builds, and never runs `pnpm dev`.
    ".next-dev/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Design assets, not app source: `docs/ui/` holds wireframe blueprints and
    // the vendored runtime that renders them (see `docs/ui/README.md`). Nothing
    // here is imported, built, or shipped, and `support.js` is generated by a
    // tool we do not own — the only way to satisfy its reports would be to edit
    // someone else's bundle or rewrite the wireframes, which is the opposite of
    // what those files are for.
    "docs/ui/**",
  ]),
]);

export default eslintConfig;
