import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Design assets, not app source: `docs/ui/` holds wireframe blueprints and
    // the vendored runtime that renders them (see `docs/ui/README.md`). Nothing
    // here is imported, built, or shipped, and `support.js` is generated by a
    // tool we do not own — the only way to satisfy its reports would be to edit
    // someone else's bundle or rewrite the wireframes, which is the opposite of
    // what those files are for.
    "docs/ui/**",
  ]),
]);

export default eslintConfig;
