#!/usr/bin/env bash
# Regenerates tasks/README.md and tasks/archive/README.md from the files on disk.
# Both are generated. The conventions themselves live in tasks/active/README.md,
# which is hand-written.
set -euo pipefail
shopt -s nullglob

cd "$(dirname "$0")/.."

# First "# " heading of a todo, falling back to its filename.
title_of() {
  local t
  t=$(awk '/^#[ \t]/ { sub(/^#[ \t]+/, ""); print; exit }' "$1")
  printf '%s' "${t:-$(basename "$1" -todo.md)}"
}

# Table rows for the todos passed in. $1 is the link prefix, relative to the index being written.
rows() {
  local prefix=$1 todo base lessons
  shift
  for todo in "$@"; do
    base=${todo%-todo.md}
    lessons=""
    if [ -f "$base-lessons.md" ]; then
      lessons="[lessons](${prefix}$(basename "$base-lessons.md"))"
    fi
    printf '| [%s](%s%s) | %s |\n' "$(title_of "$todo")" "$prefix" "$(basename "$todo")" "$lessons"
  done
}

# Newest first, by the YYYYMMDD- filename prefix.
active=(tasks/active/*-todo.md)
if [ ${#active[@]} -gt 0 ]; then
  mapfile -t active < <(printf '%s\n' "${active[@]}" | sort -r)
fi

months=(tasks/archive/[0-9][0-9][0-9][0-9]/[0-9][0-9])
if [ ${#months[@]} -gt 0 ]; then
  mapfile -t months < <(printf '%s\n' "${months[@]}" | sort -r)
fi

{
  cat <<'EOF'
# Tasks

_Generated by `scripts/tasks-index.sh`. Do not edit by hand._

Work in progress lives in `active/`, finished work in `archive/YYYY/MM/`. Naming rules,
the issue-vs-task boundary, and the templates are in [`active/README.md`](active/README.md).
The overall plan is in [`../ROADMAP.md`](../ROADMAP.md).

## Managing tasks

The bookkeeping is two scripts in [`../scripts/`](../scripts/), both registered in `package.json`.
They only move markdown around and rebuild these indexes — nothing to do with running the app.

| To | Run |
| :--- | :--- |
| Start a task | Copy `templates/todo.md` and `templates/lessons.md` into `active/` as `YYYYMMDD-<slug>-todo.md` and `YYYYMMDD-<slug>-lessons.md`, then `pnpm tasks:index` |
| Finish a task | `pnpm tasks:archive <slug>` — moves the pair into `archive/YYYY/MM/`, then rebuilds both indexes |
| Rebuild the indexes | `pnpm tasks:index` |

This file and [`archive/README.md`](archive/README.md) are built from whatever is on disk. Change
the task files, then rerun — never edit an index by hand, the next run overwrites it.

## Active

EOF

  if [ ${#active[@]} -eq 0 ]; then
    echo "Nothing in progress."
  else
    echo "| Task | Lessons |"
    echo "| :--- | :--- |"
    rows "active/" "${active[@]}"
  fi

  cat <<'EOF'

## Archive

Finished tasks are listed in [`archive/README.md`](archive/README.md), grouped by month.
EOF
} > tasks/README.md

{
  cat <<'EOF'
# Archive

_Generated by `scripts/tasks-index.sh`. Do not edit by hand._

Finished tasks, newest month first. See [`../README.md`](../README.md) for how tasks are managed.

EOF

  if [ ${#months[@]} -eq 0 ]; then
    echo "Nothing archived yet."
  else
    for dir in "${months[@]}"; do
      todos=("$dir"/*-todo.md)
      if [ ${#todos[@]} -gt 0 ]; then
        mapfile -t todos < <(printf '%s\n' "${todos[@]}" | sort -r)
        ym=${dir#tasks/archive/}
        echo "## ${ym/\//-}"
        echo
        echo "| Task | Lessons |"
        echo "| :--- | :--- |"
        rows "${ym}/" "${todos[@]}"
        echo
      fi
    done
  fi
} > tasks/archive/README.md

echo "wrote tasks/README.md and tasks/archive/README.md"
